### ISSUE TITLE
Bug regarding Central IDP and Shared IDP in Azure

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/tractus-x-umbrella#171]
## Description

For some reason the central IDP and shared IDP seeding fail when we deploy them in azure. Some times it works and some times it fails. There are are no error logs so we are not able to see why.

We are not able to login in the portal without that...

We also tried to solve increasing the resources and it didn't worked....

**Comment by evegufy** [comment]
@kss682 I discussed yesterday with @matbmoser and @dvg36 that you would approach me to get some information.
I can't reproduce and don't experience it myself, so I have no information to work with.

**Comment by evegufy** [comment]
@kss682 I think we should have a call and you show me what's happing, that's what @dvg36, @matbmoser, @JohannesARENA2036 and I discussed yesterday: that you would approach me and show me the issue. can you please send a call?

What would have been helpful to know already: You needed to change the umbrella default config in order to deploy the umbrella, right? Which config did you adjust? In the description is mentioned that you increased resources, to which values did you increase them?

**Comment by kss682** [comment]
@evegufy Sure we can have a call when are you free ?

**Comment by kss682** [comment]
@evegufy I have sent an invite.

**Comment by matbmoser** [comment]
It was a issue regarding  the resources thx @evegufy for you support
